
name: Dynamic Env Vars

on:
  workflow_dispatch:

jobs:

  setup:
    name: Hello
    runs-on: ubuntu-latest
    steps:
      - name: exporting
        run:
          echo Hello world

  export-env-vars:
    name: Demo of exporting the dynamic environment variables
    runs-on: ubuntu-latest
    needs: [setup]
    outputs:
      ENV_VARS: ${{ steps.setMyEnv.outputs.ENV_VARS }}
    steps:
      - name: exporting
        id: setMyEnv
        run:
          echo 'ENV_VARS={"VAR_THE_FIRST":"Hello","VAR_THE_SECOND":"Hello again"}' >> ${GITHUB_OUTPUT}

  import-env-vars:
    name: Demo of importing the dynamic environment variables
    runs-on: ubuntu-latest
    needs: [export-env-vars]
    env: ${{ fromJson(needs.export-env-vars.outputs.ENV_VARS) }}
    steps:
      - name: importing
        run:
          env | grep VAR_THE
