
name: Dynamic Env Vars

on:
  workflow_dispatch:

jobs:

  export-env-vars:
    name: Demo of exporting the dynamic environment variables
    runs-on: ubuntu-latest
    outputs:
      ENV_SETTINGS: ${{ steps.setMyEnv.outputs.MY_OBJECT }}
    steps:
      - name: export
        id: setMyEnv
        run:
          echo 'MY_OBJECT={"VAR_THE_FIRST":"Hello","VAR_THE_SECOND":"Hello again"}' >> ${GITHUB_OUTPUT}

  import-env-vars:
    name: Demo of importing the dynamic environment variables
    runs-on: ubuntu-latest
    needs: [export-env-vars]
    env: ${{ fromJson(needs.export-env-vars.outputs.ENV_SETTINGS) }}
    steps:
      - name: imported
        run:
          env | grep VAR_THE

