
name: Dynamic Env Vars

on:
  push:

jobs:
  export-env-vars:
    name: Demo of exporting the dynamic environment variables
    runs-on: ubuntu-latest
    outputs:
      ENV_VARS: ${{ steps.setMyEnv.outputs.ENV_VARS }}
    steps:
      - name: exporting
        id: setMyEnv
        run:
          echo 'ENV_VARS={"VAR_THE_FIRST":"Hello","VAR_THE_SECOND":"Hello again"}' >> ${GITHUB_OUTPUT}

  import-env-vars:
    name: Demo of importing the dynamic environment variables
    runs-on: ubuntu-latest
    needs: [export-env-vars]
    env:
      WRAPPED: ${{ toJson(fromJson(needs.export-env-vars.outputs.ENV_VARS)) }}
    steps:
      - name: importing
        run: |
          jq -r 'keys[] as $k | "export \($k)=\(.[$k])"' <<< "${{ env.WRAPPED }}"
          env | grep VAR_THE

      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build and push Docker image to ECR
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context:  .
          no-cache: true
          push:     false
          tags:     cyberdojo/dynamic-env-vars
#          build-args: |
#            COMMIT_SHA=${{ github.sha }}
#            BASE_IMAGE=${{ inputs.base_image }}
