name: Main

on:
  push:

jobs:

  generate-deploy-matrix:
    name: Generate Job Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Generate matrix
        id: set-matrix
        run: |
          json="{\"include\": [{\"service\": \"alpha\"},{\"service\": \"beta\"}]}"
          echo "matrix=${json}" >> ${GITHUB_OUTPUT}

  deploy-all:
    needs: [generate-deploy-matrix]
    name: Check
    runs-on: ubuntu-latest
    if: needs.generate-matrix.outputs.matrix != ''
    strategy:
      matrix: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}

    steps:
      - run:
          echo "deploy :${{ matrix.service }}:"


  result:
    needs: [deploy-all]
    runs-on: ubuntu-latest
    steps:
      - run:
          echo "Got to here"

