name: Main

on:
  push:

jobs:

  generate-matrix:
    name: Generate Job Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Generate matrix
        id: set-matrix
        run: |
          json="{\"include\": [{\"in\":{\"service\": \"alpha\"}},{\"in\": \"service\": \"beta\"}}]}"
          echo "matrix=${json}" >> ${GITHUB_OUTPUT}

  deploy:
    needs: [generate-matrix]
    name: Check
    runs-on: ubuntu-latest
    if: needs.generate-matrix.outputs.matrix != ''
    strategy:
      matrix: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}

    steps:
      - run: |
          echo "deploy :${{ matrix.in }}:"
          if [ "${{ matrix.in.service }}" == "alpha" ]; then
            return 0
          else
            return 1
          fi


  result:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - run:
          echo "Got to here"

