name: Main

on:
  push:

jobs:

  setup:
    name: Generate Job Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix_include: ${{ steps.generate.outputs.matrix_include }}
    env:
      JSON: >-
        [
          {"incoming":{"service": "alpha"}},
          {"incoming":{"service": "beta"}}
        ]
    steps:
      - name: Generate matrix-include
        id: generate
        run:
          echo "matrix_include=$(jq -r -c . <<< ${JSON})" >> ${GITHUB_OUTPUT}

  deploy:
    needs: [setup]
    name: Check
    runs-on: ubuntu-latest
    if: needs.setup.outputs.matrix_include != ''
    strategy:
      matrix:
        include: ${{ fromJSON(needs.setup.outputs.matrix_include) }}

    steps:
      - run: |
          echo "deploy :${{ matrix.incoming.service }}:"
          if [ "${{ matrix.incoming.service }}" == "alpha" ]; then
            exit 0
          else
            exit 1
          fi


  result:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - run:
          echo "Got to here"

