name: Main

on:
  push:

jobs:

  setup:
    name: Generate Job Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix_include: ${{ steps.generate.outputs.matrix_include }}
    env:
      JSON: >-
        [
          {"incoming":{"service": "alpha"}, "outgoing":{"service": "xalpha"}},
          {"incoming":{"service": "beta" }, "outgoing":{"service": "xalpha"}}
        ]
    steps:
      - name: Generate matrix-include
        id: generate
        run:
          echo "matrix_include=$(jq . <<< "${JSON}")"
          echo "matrix_include=$(jq -r --compact-output . <<< "${JSON}")" >> ${GITHUB_OUTPUT}

  deploy:
    needs: [setup]
    name: Check
    runs-on: ubuntu-latest
    if: needs.setup.outputs.matrix_include != ''
    strategy:
      matrix:
        include: ${{ fromJSON(needs.setup.outputs.matrix_include) }}
    env:
      MATRIX:   ${{ fromJSON(matrix) }}
      #INCOMING: ${{ fromJSON(toJSON(matrix)).incoming }}
      #OUTGOING: ${{ fromJSON(toJSON(matrix)).outgoing }}
    steps:
      - run: |
          echo "matrix: $(jq . <<< "${MATRIX}")"
#          echo "incoming: $(jq . <<< "${INCOMING}")"
#          echo "outgoing: $(jq . <<< "${OUTGOING}")"
#
#          if [ "$(jq '.service' <<< "${INCOMING}")" == "alpha" ]; then
#            exit 0
#          else
#            exit 1
#          fi


  result:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - run:
          echo "Got to here"

